INSERT INTO [dbo].[Type_Items] ([Id], [name]) VALUES (3, N'Amulette')
INSERT INTO [dbo].[Type_Items] ([Id], [name]) VALUES (8, N'Anneau')
INSERT INTO [dbo].[Type_Items] ([Id], [name]) VALUES (11, N'Arme à 1 main')
INSERT INTO [dbo].[Type_Items] ([Id], [name]) VALUES (10, N'Arme à 2 mains')
INSERT INTO [dbo].[Type_Items] ([Id], [name]) VALUES (7, N'Bottes')
INSERT INTO [dbo].[Type_Items] ([Id], [name]) VALUES (13, N'Bouclier')
INSERT INTO [dbo].[Type_Items] ([Id], [name]) VALUES (2, N'Cape')
INSERT INTO [dbo].[Type_Items] ([Id], [name]) VALUES (1, N'Casque')
INSERT INTO [dbo].[Type_Items] ([Id], [name]) VALUES (6, N'Ceinture')
INSERT INTO [dbo].[Type_Items] ([Id], [name]) VALUES (12, N'Dague')
INSERT INTO [dbo].[Type_Items] ([Id], [name]) VALUES (14, N'Emblème')
INSERT INTO [dbo].[Type_Items] ([Id], [name]) VALUES (4, N'Epaulettes')
INSERT INTO [dbo].[Type_Items] ([Id], [name]) VALUES (15, N'Familier')
INSERT INTO [dbo].[Type_Items] ([Id], [name]) VALUES (16, N'Monture')
INSERT INTO [dbo].[Type_Items] ([Id], [name]) VALUES (5, N'Plastron')
